steps:
- name: gcr.io/cloud-builders/docker
  id: docker-build
  entrypoint: bash
  args:
  - '-c'
  - |
    docker build -t gcr.io/sre-sray-development/helloworld
    docker push gcr.io/sre-sray-development/helloworld
        
- name: gcr.io/cloud-builders/kubectl
  id: deploy
  entrypoint: bash
  args:
  - '-c'
  - |
    glcoud container clusters get-credentials --project=sre-sray-development test
    kubectl apply -f deployment.yaml